application: wwqgtxx-monitor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /start_fetch
  script: fetch_handler.app
  login: admin

- url: /start_list
  script: list_handler.app
  login: admin

- url: /start_email
  script: email_handler.app
  login: admin

- url: /api/?.*
  script: api_handler.app

- url: /page/?.*
  script: page_handler.app

- url: /
  script: index_handler.app

